# Base configs
baseurl: "https://urbanai.dev"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "UrbanAI"
subtitle: ".dev"
author: "Max Forslund"
header:
 title: "UrbanAI"
 subtitle: ".dev"
footer:
 name: "Welcome to UrbanAI"
 bio: "We make AI Art and put it on clothing and posters for you to enjoy. Here we will showcase our artwork."
 github: ""
web_design: "MF"
social_urls:
  instagram: "https://www.instagram.com/urbanai.uf"
